# Generated by Django 5.0.4 on 2024-04-14 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('night_prayer', models.BooleanField()),
                ('reciting_quran', models.BooleanField()),
                ('reading_book', models.BooleanField()),
                ('practicing_programming', models.BooleanField()),
                ('visiting_person', models.BooleanField()),
                ('receiving_person', models.BooleanField()),
                ('visiting_place', models.BooleanField()),
                ('sleeping', models.BooleanField()),
                ('relaxing', models.BooleanField()),
                ('note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PersonName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Programming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100)),
                ('framework', models.CharField(max_length=100)),
                ('note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='QuranSurah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_from', models.TimeField()),
                ('time_to', models.TimeField()),
                ('note', models.TextField()),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.activitytype')),
            ],
        ),
        migrations.AddField(
            model_name='activitytype',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.book'),
        ),
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('note', models.TextField()),
                ('after_midnight', models.ManyToManyField(related_name='diary_activity_after_midnight_rel', to='activities.activity')),
                ('after_noon', models.ManyToManyField(related_name='diary_activityType_recited_quran_surahs_rel', to='activities.activity')),
                ('before_midnight', models.ManyToManyField(related_name='diary_activity_before_midnight_rel', to='activities.activity')),
                ('during_day', models.ManyToManyField(related_name='diary_activity_during_day_rel', to='activities.activity')),
                ('evening', models.ManyToManyField(related_name='diary_activity_after_noon_rel', to='activities.activity')),
                ('morning', models.ManyToManyField(related_name='diary_activity_morning_rel', to='activities.activity')),
            ],
        ),
        migrations.AddField(
            model_name='activitytype',
            name='received_persons',
            field=models.ManyToManyField(related_name='activityType_received_persons_rel', to='activities.person'),
        ),
        migrations.AddField(
            model_name='activitytype',
            name='visited_persons',
            field=models.ManyToManyField(related_name='activityType_visited_persons_rel', to='activities.person'),
        ),
        migrations.AddField(
            model_name='person',
            name='first_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_personname_first_rel', to='activities.personname'),
        ),
        migrations.AddField(
            model_name='person',
            name='fourth_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_personname_fourth_rel', to='activities.personname'),
        ),
        migrations.AddField(
            model_name='person',
            name='second_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_personname_second_rel', to='activities.personname'),
        ),
        migrations.AddField(
            model_name='person',
            name='third_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_personname_third_rel', to='activities.personname'),
        ),
        migrations.AddField(
            model_name='person',
            name='current_residence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.place'),
        ),
        migrations.AddField(
            model_name='person',
            name='prior_residences',
            field=models.ManyToManyField(related_name='person_place_prior_residences_rel', to='activities.place'),
        ),
        migrations.AddField(
            model_name='activitytype',
            name='visited_places',
            field=models.ManyToManyField(to='activities.place'),
        ),
        migrations.AddField(
            model_name='activitytype',
            name='programming',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.programming'),
        ),
        migrations.AddField(
            model_name='activitytype',
            name='night_prayer_surahs',
            field=models.ManyToManyField(related_name='activityType_night_prayer_surahs_rel', to='activities.quransurah'),
        ),
        migrations.AddField(
            model_name='activitytype',
            name='quran_surahs',
            field=models.ManyToManyField(related_name='activityType_recited_quran_surahs_rel', to='activities.quransurah'),
        ),
    ]
