# Generated by Django 5.0.6 on 2024-06-09 12:57

import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('NIGHT_PRAYER', 'Night Prayer'), ('RECITING_QURAN', 'Reciting Quran'), ('READING_BOOK', 'Reading Book'), ('PRACTICING_PROGRAMMING', 'Practicing Programming'), ('VISITING_PERSON', 'Visiting Person'), ('RECEIVING_PERSON', 'Receiving Person'), ('VISITING_DOCTOR', 'Visiting Dotor'), ('VISITING_PLACE', 'Visiting Place'), ('CHANGING_RESIDENCE', 'Changing Residence'), ('PURCHASING', 'Purchasing'), ('REVIEWING_LECTURE', 'Reviewing Lecture'), ('REVIEWING_GENERAL_TOPIC', 'Reviewing General Topic'), ('SLEEPING', 'Sleeping'), ('RELAXING', 'Relaxing'), ('CLEANING_CLOTHS', 'Cleaning Cloths'), ('CLEANING_HOME', 'Cleaning Home'), ('SHAVING', 'Shaving'), ('PREPARING_FOOD', 'Preparing Food')], default='NIGHT_PRAYER', max_length=30)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('note', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=48, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=48, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PersonName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=48, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=48, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Programming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100)),
                ('framework', models.CharField(max_length=100)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=4, max_digits=48, null=True)),
                ('currency', models.CharField(choices=[('EGP', 'EGP'), ('USD', 'USD'), ('EUR', 'EUR'), ('SDG', 'SDG')], default='EGP', max_length=10)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuranSurah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_from', models.TimeField()),
                ('time_to', models.TimeField()),
                ('note', models.TextField(blank=True, null=True)),
                ('duration', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.functions.datetime.Extract('time_to', 'hour'), '-', django.db.models.functions.datetime.Extract('time_from', 'hour')), '+', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.functions.datetime.Extract('time_to', 'minute'), '-', django.db.models.functions.datetime.Extract('time_from', 'minute')), '/', models.Value(60))), output_field=models.FloatField())),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.activitytype')),
            ],
            options={
                'verbose_name_plural': 'Activities',
            },
        ),
        migrations.AddField(
            model_name='activitytype',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.book'),
        ),
        migrations.AddField(
            model_name='activitytype',
            name='visited_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.doctor'),
        ),
        migrations.AddField(
            model_name='activitytype',
            name='prepared_food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.food'),
        ),
        migrations.AddField(
            model_name='activitytype',
            name='general_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.generaltopic'),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.institute')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.course')),
            ],
        ),
        migrations.AddField(
            model_name='activitytype',
            name='lecture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.lecture'),
        ),
        migrations.AddField(
            model_name='activitytype',
            name='purchase_market',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.market'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.person'),
        ),
        migrations.AddField(
            model_name='activitytype',
            name='received_persons',
            field=models.ManyToManyField(blank=True, related_name='received_persons_set', to='activities.person'),
        ),
        migrations.AddField(
            model_name='activitytype',
            name='visited_persons',
            field=models.ManyToManyField(blank=True, related_name='visited_persons_activityType_set', to='activities.person'),
        ),
        migrations.AddField(
            model_name='person',
            name='fifth_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fifth_name_person_set', to='activities.personname'),
        ),
        migrations.AddField(
            model_name='person',
            name='first_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_name_person_set', to='activities.personname'),
        ),
        migrations.AddField(
            model_name='person',
            name='fourth_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fourth_name_person_set', to='activities.personname'),
        ),
        migrations.AddField(
            model_name='person',
            name='second_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_name_person_set', to='activities.personname'),
        ),
        migrations.AddField(
            model_name='person',
            name='seventh_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seventh_name_person_set', to='activities.personname'),
        ),
        migrations.AddField(
            model_name='person',
            name='sixth_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sixth_name_person_set', to='activities.personname'),
        ),
        migrations.AddField(
            model_name='person',
            name='third_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third_name_person_set', to='activities.personname'),
        ),
        migrations.AddField(
            model_name='person',
            name='current_residence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.place'),
        ),
        migrations.AddField(
            model_name='person',
            name='prior_residences',
            field=models.ManyToManyField(blank=True, related_name='person_place_prior_residences_rel', to='activities.place'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('note', models.TextField(null=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.eventtype')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.place')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.place'),
        ),
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('alfajr', models.TimeField()),
                ('dawn', models.TimeField()),
                ('almaghrib', models.TimeField()),
                ('fasting', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, null=True)),
                ('after_midnight', models.ManyToManyField(related_name='after_midnight_diary_set', to='activities.activity')),
                ('before_midnight', models.ManyToManyField(related_name='before_midnight_diary_set', to='activities.activity')),
                ('during_day', models.ManyToManyField(related_name='during_day_diary_set', to='activities.activity')),
                ('evening', models.ManyToManyField(related_name='evening_diary_set', to='activities.activity')),
                ('morning', models.ManyToManyField(related_name='morning_diary_set', to='activities.activity')),
                ('residence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.place')),
            ],
            options={
                'verbose_name_plural': 'Diaries',
            },
        ),
        migrations.AddField(
            model_name='activitytype',
            name='moved_to_residence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moved_to_residence_set', to='activities.place'),
        ),
        migrations.AddField(
            model_name='activitytype',
            name='visited_places',
            field=models.ManyToManyField(blank=True, to='activities.place'),
        ),
        migrations.AddField(
            model_name='activitytype',
            name='programming',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.programming'),
        ),
        migrations.AddField(
            model_name='activitytype',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.purchase'),
        ),
        migrations.AddField(
            model_name='activitytype',
            name='night_prayer_surahs',
            field=models.ManyToManyField(blank=True, related_name='night_prayer_surah_activityType_set', to='activities.quransurah'),
        ),
        migrations.AddField(
            model_name='activitytype',
            name='quran_surahs',
            field=models.ManyToManyField(blank=True, related_name='recited_quran_surah_activityType_set', to='activities.quransurah'),
        ),
    ]
