# Generated by Django 5.0.6 on 2024-06-09 12:59
import re

from django.db import migrations


def insert_quran_surah_s(apps, schema_editor):
    quran_surah_class = apps.get_model('activities', 'QuranSurah')

    r_en = re.compile(r'^([^(]*)\(')
    r_ar = re.compile(r'^[0-9]*-([^0-9]*)[0-9]*-([^0-9]*)[0-9]*-([^0-9]*)')
    surah_en = []
    surah_ar = []
    with open("activities/files/quran_surah_en.txt", encoding='utf8') as file_en:
        for line_en in file_en:
            surah_en.append(r_en.search(line_en).groups(1)[0].strip())

    # If you provide a negative value to step, then the slicing runs backward, meaning from right to left.
    # For example, if you set step equal to -1, then you can build a slice that
    # retrieves all the characters in reverse order
    with open("activities/files/quran_surah_ar.txt", encoding='utf8') as file_ar:
        for line_ar in file_ar:
            groups = r_ar.search(line_ar).groups()
            # surah_ar.append(groups[0].strip()[slice(None, None, -1)])
            # surah_ar.append(groups[1].strip()[slice(None, None, -1)])
            # surah_ar.append(groups[2].strip()[slice(None, None, -1)])
            # surah_ar.append(groups[0].strip()[::-1])
            # surah_ar.append(groups[1].strip()[::-1])
            # surah_ar.append(groups[2].strip()[::-1])
            # surah_ar.append("".join(reversed(groups[0].strip())))
            # surah_ar.append("".join(reversed(groups[1].strip())))
            # surah_ar.append("".join(reversed(groups[2].strip())))
            surah_ar.append(groups[0].strip())
            surah_ar.append(groups[1].strip())
            surah_ar.append(groups[2].strip())

    i = 1
    combined_list = []
    for a, e in zip(surah_ar, surah_en):
        combined_list.append((i, a, e))
        i += 1

    for n, a, e in combined_list:
        quran_surah_class.objects.create(name_ar=a, name_en=e, number=n)


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_quran_surah_s)
    ]
