# Generated by Django 5.0.4 on 2024-04-15 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_institute_lecture_market_purchase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.course'),
        ),
        migrations.AlterField(
            model_name='activitytype',
            name='market',
            field=models.ManyToManyField(to='activities.market'),
        ),
        migrations.AlterField(
            model_name='activitytype',
            name='night_prayer_surahs',
            field=models.ManyToManyField(related_name='night_prayer_surah_activityType_set', to='activities.quransurah'),
        ),
        migrations.AlterField(
            model_name='activitytype',
            name='quran_surahs',
            field=models.ManyToManyField(related_name='recited_quran_surah_activityType_set', to='activities.quransurah'),
        ),
        migrations.AlterField(
            model_name='activitytype',
            name='received_persons',
            field=models.ManyToManyField(related_name='received_persons_set', to='activities.person'),
        ),
        migrations.AlterField(
            model_name='activitytype',
            name='visited_persons',
            field=models.ManyToManyField(related_name='visited_persons_activityType_set', to='activities.person'),
        ),
        migrations.AlterField(
            model_name='activitytype',
            name='visited_places',
            field=models.ManyToManyField(to='activities.place'),
        ),
        migrations.AlterField(
            model_name='person',
            name='prior_residences',
            field=models.ManyToManyField(related_name='person_place_prior_residences_rel', to='activities.place'),
        ),
    ]
