# Generated by Django 5.0.4 on 2024-04-21 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_event_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='after_noon',
        ),
        migrations.AddField(
            model_name='activitytype',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.purchase'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activitytype',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.book'),
        ),
        migrations.AlterField(
            model_name='activitytype',
            name='lecture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.lecture'),
        ),
        migrations.AlterField(
            model_name='activitytype',
            name='market',
            field=models.ManyToManyField(blank=True, to='activities.market'),
        ),
        migrations.AlterField(
            model_name='activitytype',
            name='night_prayer_surahs',
            field=models.ManyToManyField(blank=True, related_name='night_prayer_surah_activityType_set', to='activities.quransurah'),
        ),
        migrations.AlterField(
            model_name='activitytype',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activitytype',
            name='programming',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.programming'),
        ),
        migrations.AlterField(
            model_name='activitytype',
            name='quran_surahs',
            field=models.ManyToManyField(blank=True, related_name='recited_quran_surah_activityType_set', to='activities.quransurah'),
        ),
        migrations.AlterField(
            model_name='activitytype',
            name='received_persons',
            field=models.ManyToManyField(blank=True, related_name='received_persons_set', to='activities.person'),
        ),
        migrations.AlterField(
            model_name='activitytype',
            name='visited_persons',
            field=models.ManyToManyField(blank=True, related_name='visited_persons_activityType_set', to='activities.person'),
        ),
        migrations.AlterField(
            model_name='activitytype',
            name='visited_places',
            field=models.ManyToManyField(blank=True, to='activities.place'),
        ),
        migrations.AlterField(
            model_name='book',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diary',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='institute',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='market',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='current_residence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.place'),
        ),
        migrations.AlterField(
            model_name='person',
            name='fifth_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fifth_name_person_set', to='activities.personname'),
        ),
        migrations.AlterField(
            model_name='person',
            name='prior_residences',
            field=models.ManyToManyField(blank=True, related_name='person_place_prior_residences_rel', to='activities.place'),
        ),
        migrations.AlterField(
            model_name='person',
            name='seventh_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seventh_name_person_set', to='activities.personname'),
        ),
        migrations.AlterField(
            model_name='person',
            name='sixth_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sixth_name_person_set', to='activities.personname'),
        ),
        migrations.AlterField(
            model_name='place',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='programming',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
