# Generated by Django 5.0.4 on 2024-04-26 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_remove_diary_after_noon_activitytype_purchase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=48, null=True),
        ),
        migrations.AddField(
            model_name='market',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=48, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=48, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=48, null=True),
        ),
    ]
