# Generated by Django 5.0.4 on 2024-04-27 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0008_market_latitude_market_longitude_place_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitytype',
            name='visiting_doctor',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.place')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.person')),
            ],
        ),
        migrations.AddField(
            model_name='activitytype',
            name='visited_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.doctor'),
        ),
    ]
