# Generated by Django 5.0.6 on 2024-05-22 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0009_activitytype_visiting_doctor_doctor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='diary',
            options={'verbose_name_plural': 'Diaries'},
        ),
        migrations.AddField(
            model_name='activitytype',
            name='moved_to_residence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moved_to_residence_set', to='activities.place'),
        ),
        migrations.AddField(
            model_name='activitytype',
            name='moving_to_different_residence',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activitytype',
            name='preparing_food',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diary',
            name='almaghrib',
            field=models.TimeField(),
        ),
        migrations.AddField(
            model_name='purchase',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('SDG', 'SDG')], default='EGP', max_length=10),
        ),
        migrations.AddField(
            model_name='activitytype',
            name='prepared_food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.food'),
        ),
    ]
