# Generated by Django 5.0.6 on 2024-05-22 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0010_food_alter_activity_options_alter_diary_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.place'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='currency',
            field=models.CharField(choices=[('EGP', 'EGP'), ('USD', 'USD'), ('EUR', 'EUR'), ('SDG', 'SDG')], default='EGP', max_length=10),
        ),
    ]
