# Generated by Django 5.0.6 on 2024-05-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0011_event_place_alter_purchase_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitytype',
            name='cleaning_home',
            field=models.BooleanField(default=False),
        ),
    ]
