# Generated by Django 5.0.6 on 2024-05-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0013_generaltopic_activitytype_reviewing_general_topic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitytype',
            name='type',
            field=models.CharField(choices=[('NIGHT_PRAYER', 'Night Prayer'), ('RECITING_QURAN', 'Reciting Quran'), ('READING_BOOK', 'Reading Book'), ('PRACTICING_PROGRAMMING', 'Practicing Programming'), ('VISITING_PERSON', 'Visiting Person'), ('RECEIVING_PERSON', 'Receiving Person'), ('VISITING_DOCTOR', 'Visiting Dotor'), ('VISITING_PLACE', 'Visiting Place'), ('CHANGING_RESIDENCE', 'Changing Residence'), ('PURCHASING', 'Purchasing'), ('REVIEWING_LECTURE', 'Reviewing Lecture'), ('REVIEWING_GENERAL_TOPIC', 'Reviewing General Topic'), ('SLEEPING', 'Sleeping'), ('RELAXING', 'Relaxing'), ('CLEANING_CLOTHS', 'Cleaning Cloths'), ('CLEANING_HOME', 'Cleaning Home'), ('SHAVING', 'Shaving'), ('PREPARING_FOOD', 'Preparing Food')], default='NIGHT_PRAYER', max_length=30),
        ),
    ]
