# Generated by Django 5.0.6 on 2024-05-27 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0014_activitytype_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitytype',
            name='cleaning_clothes',
        ),
        migrations.RemoveField(
            model_name='activitytype',
            name='cleaning_home',
        ),
        migrations.RemoveField(
            model_name='activitytype',
            name='moving_to_different_residence',
        ),
        migrations.RemoveField(
            model_name='activitytype',
            name='night_prayer',
        ),
        migrations.RemoveField(
            model_name='activitytype',
            name='practicing_programming',
        ),
        migrations.RemoveField(
            model_name='activitytype',
            name='preparing_food',
        ),
        migrations.RemoveField(
            model_name='activitytype',
            name='purchasing',
        ),
        migrations.RemoveField(
            model_name='activitytype',
            name='reading_book',
        ),
        migrations.RemoveField(
            model_name='activitytype',
            name='receiving_person',
        ),
        migrations.RemoveField(
            model_name='activitytype',
            name='reciting_quran',
        ),
        migrations.RemoveField(
            model_name='activitytype',
            name='relaxing',
        ),
        migrations.RemoveField(
            model_name='activitytype',
            name='reviewing_general_topic',
        ),
        migrations.RemoveField(
            model_name='activitytype',
            name='reviewing_lecture',
        ),
        migrations.RemoveField(
            model_name='activitytype',
            name='shaving',
        ),
        migrations.RemoveField(
            model_name='activitytype',
            name='sleeping',
        ),
        migrations.RemoveField(
            model_name='activitytype',
            name='visiting_doctor',
        ),
        migrations.RemoveField(
            model_name='activitytype',
            name='visiting_person',
        ),
        migrations.RemoveField(
            model_name='activitytype',
            name='visiting_place',
        ),
    ]
