# Generated by Django 5.0.6 on 2024-06-04 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0016_activity_duration'),
    ]

    def migrate_m2m_to_fk(apps, schema_editor):
        ActivityType = apps.get_model("activities", "ActivityType")
        for activity_type in ActivityType.objects.all():
            if activity_type.type == 'PURCHASING':
                activity_type.purchase_market = activity_type.market.first()
                activity_type.save()

    operations = [
        migrations.AddField(
            model_name='activitytype',
            name='purchase_market',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.market'),
        ),
        migrations.AlterField(
            model_name='activitytype',
            name='market',
            field=models.ManyToManyField(blank=True, related_name='market_activityType_set', to='activities.market'),
        ),
        migrations.RunPython(migrate_m2m_to_fk),
    ]
