# Generated by Django 5.0.6 on 2024-06-04 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0017_activitytype_purchase_market_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitytype',
            name='market',
        ),
    ]
