# Generated by Django 5.0.6 on 2024-06-10 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('light_novels', '0002_chapter_flag_alter_chapter_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='is_name',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='word',
            constraint=models.UniqueConstraint(fields=('text',), name='unique_word'),
        ),
    ]
