# Generated by Django 5.0.6 on 2024-06-11 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('light_novels', '0004_alter_profanitycategory_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='badsentence',
            constraint=models.UniqueConstraint(fields=('sentence', 'category'), name='unique_bad_sentence'),
        ),
        migrations.AddConstraint(
            model_name='badword',
            constraint=models.UniqueConstraint(fields=('word', 'category'), name='unique_bad_word'),
        ),
        migrations.AddConstraint(
            model_name='chapterword',
            constraint=models.UniqueConstraint(fields=('word', 'chapter'), name='unique_chapter_word'),
        ),
        migrations.AddConstraint(
            model_name='sentence',
            constraint=models.UniqueConstraint(fields=('text',), name='unique_sentence'),
        ),
    ]
